version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crc-dynamodb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12lkd9h2oeinw"
s3_prefix = "crc-dynamodb"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
